\documentclass{article}

%headers and footers
\usepackage{fancyhdr}
\usepackage{array}
\pagestyle{fancyplain}

\usepackage{sidecap}
\usepackage{subfigure}
\usepackage{float}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{setspace}

\fancyhfoffset[LE, LO, RE, RO]{.1in}

\rhead{$671k27$}
\chead{}
\lhead{}

\lfoot{\includegraphics[width=0.1\textwidth]{/home/zhangz/hts/scripts/bamchop.1.01/logo.jpg} {\bfseries Center for Biomedical Informatics at CHOP}}
\cfoot{}
\rfoot{\fancyplain{}{\thepage}}

\renewcommand{\footrulewidth}{0.4pt}

\addtolength{\voffset}{-54pt}
\addtolength{\hoffset}{-72pt}
\addtolength{\textwidth}{144pt}
\addtolength{\textheight}{108pt}


%hyperlink setup
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{underscore}
\usepackage{appendix}
\definecolor{dark-red}{rgb}{0.4,0.15,0.15}
\definecolor{dark-blue}{rgb}{0.15,0.15,0.4}
\definecolor{medium-blue}{rgb}{0,0,0.5}
\hypersetup{
  colorlinks, linkcolor={dark-red},
  citecolor={dark-blue}, urlcolor={medium-blue}
}

\setlength{\headheight}{10pt}
\setlength{\parindent}{0pt} 
\setlength{\parskip}{1ex}
\setlength{\tabcolsep}{5pt}
\setlength{\extrarowheight}{1.5pt}

\usepackage{Sweave}
\begin{document}
\begin{titlepage}
\title{ENCODE CD14+Monocyte Histone ChIP-seq: 671k27}
\author{Prepared by Zhe Zhang}
\maketitle
\tableofcontents
\end{titlepage}




\begin{center}
\includegraphics[width=7in, height=8.5in]{bamchop-landscape}
\end{center}
\pagebreak

\newpage
\section{Introduction}
\begin{description}
\item[\large{Project:}] 
\item[\large{Sample name:}] 671k27
\item[\large{Genome name:}] hg19
\end{description}

\subsection{BAM file}
\begin{description}
\item[\large{Size:}] 1.46 GB
\item[\large{Created:}] 2013-04-29 11:46:49
\item[\large{Modified:}] 2013-04-29 07:33:57
\item[\large{Location:}]  > home > zhangz > hts > projects > ks001 > 2013-04_BGI_ChIPseq > bams > novoalign_671k27_aligned.bam
\end{description}

\subsection{Summary statisitics}
\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|}
  \hline
  \rowcolor[gray]{0.9} \hline
Number of chromosomes & 24 \\ 
  Total reference size (bp) & 3,095,677,412 \\ 
   \rowcolor[gray]{0.9}Total effective size (bp) & 2,897,316,137 \\ 
  Total entries & 27,158,306 \\ 
   \rowcolor[gray]{0.9}Total mapped reads & 2,063,686 \\ 
  Total upmapped reads & 0 \\ 
   \rowcolor[gray]{0.9}Total mappings & 27,158,306 \\ 
  Total mapping locations & 1,853,567 \\ 
   \rowcolor[gray]{0.9}Base N\% & 0.0031 \\ 
  (G+C)\% & 46.91 \\ 
   \rowcolor[gray]{0.9}Mapped to forward strand\% & 50.01 \\ 
  Duplicated mapping reads\% & 13.4 \\ 
   \rowcolor[gray]{0.9}Best sequencing quality & 41 \\ 
  Average sequencing quality & 38.77 \\ 
   \rowcolor[gray]{0.9}Maximum mapping length (bp) & 49 \\ 
  Minimum mapping length (bp) & 25 \\ 
   \rowcolor[gray]{0.9}Average mapping length (bp) & 48.5 \\ 
  Best mapping quality & 70 \\ 
   \rowcolor[gray]{0.9}Average mapping quality & 45.49 \\ 
  Highest sequencing depth & 9,965 \\ 
   \rowcolor[gray]{0.9}Average sequencing depth & 0.034 \\ 
  Mapped reads per kilobase & 0.71 \\ 
   \hline
\end{tabular}\caption{\textbf{Summary statistics}
\newline
\textbf{Effective size:} chromosome length without assembly gaps.
\newline
\textbf{Sequencing quality score:} assigned by the resequencing machine to indicate base calling confidence. 
\newline
\textbf{Mapping quality score:}  assigned by the alignment program to indicating mapping confidence.
\newline
\textbf{Mapping location:} strand-specific chromosomal location mapped to by the first base of one or more reads.
\newline
\textbf{Duplicated mapping:} the first base of multiple reads mapped to the same strand and chromosomal location.
}
\end{SCtable}

\pagebreak
\section{Read count and sequencing coverage}
This section summarizes the sequencing depth of reference chromosomes. Sequencing depth equals how many times a nucleotide base was sequenced.

\subsection{Depth categories}
\begin{SCtable}[1][!ht]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Depth & Count & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
Depth=0 & 2,776,387,677 & 97.03 \\ 
  Depth$>$=1 & 84,944,929 &  2.97 \\ 
   \rowcolor[gray]{0.9}Depth$>$=5 & 225,580 &  0.01 \\ 
  Depth$>$=10 & 100,653 &  0.00 \\ 
   \rowcolor[gray]{0.9}Depth$>$=20 & 43,408 &  0.00 \\ 
  Depth$>$=30 & 26,048 &  0.00 \\ 
   \rowcolor[gray]{0.9}Depth$>$=50 & 12,256 &  0.00 \\ 
  Depth$>$=100 & 5,637 &  0.00 \\ 
   \rowcolor[gray]{0.9}Depth$>$=1000 & 1,642 &  0.00 \\ 
  Depth=9965 & 1 &  0.00 \\ 
   \hline
\end{tabular}\caption{\textbf{Depth by cutoffs.} Number and percentage of genomic locations (single bases) having the same or higher sequencing depth than given values.}
\end{SCtable}

\subsection{Depth by chromosome}
\begin{center}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\tiny
\begin{longtable}{|r|r|r|r|r|r|r|r|}
\caption{Sequencing depth by chromosome} \\ 
  \hline
Chromosome & Chromosome\_length & Effecitive\_size & Total\_reads & Unique\_mapping & Average\_depth & Maximum\_depth & Maximum\_location \\ 
  \hline
chr1 & 249,250,621 & 225,280,621 & 183,108 & 155,787 & 0.04 & 5,721 &  91,092,890 \\ 
   \rowcolor[gray]{0.9}chr2 & 243,199,373 & 238,207,373 & 181,440 & 153,048 & 0.04 & 5,224 & 128,285,576 \\ 
  chr3 & 198,022,430 & 194,797,140 & 115,158 & 111,578 & 0.03 &   165 &  52,466,861 \\ 
   \rowcolor[gray]{0.9}chr4 & 191,154,276 & 187,661,676 & 125,170 & 107,384 & 0.03 & 9,965 &  66,939,006 \\ 
  chr5 & 180,915,260 & 177,695,260 & 112,242 & 105,348 & 0.03 & 3,322 & 171,332,108 \\ 
   \rowcolor[gray]{0.9}chr6 & 171,115,067 & 167,395,067 & 108,718 & 103,598 & 0.03 & 1,278 & 130,184,088 \\ 
  chr7 & 159,138,663 & 155,353,663 & 101,563 &  97,765 & 0.03 &   116 &  58,669,050 \\ 
   \rowcolor[gray]{0.9}chr8 & 146,364,022 & 142,888,922 & 112,740 &  88,910 & 0.04 & 7,817 &  67,487,295 \\ 
  chr9 & 141,213,431 & 120,143,431 &  82,376 &  79,488 & 0.03 &    89 &  47,511,230 \\ 
   \rowcolor[gray]{0.9}chr10 & 135,534,747 & 131,314,747 & 101,824 &  94,676 & 0.04 &   271 &  39,020,270 \\ 
  chr11 & 135,006,516 & 131,129,516 &  94,504 &  86,910 & 0.03 & 2,688 &  73,980,570 \\ 
   \rowcolor[gray]{0.9}chr12 & 133,851,895 & 130,481,895 &  90,459 &  81,721 & 0.03 & 4,334 &  20,544,443 \\ 
  chr13 & 115,169,878 &  95,589,878 &  58,679 &  53,277 & 0.03 & 1,329 &  12,398,369 \\ 
   \rowcolor[gray]{0.9}chr14 & 107,349,540 &  88,289,540 &  58,875 &  55,083 & 0.03 & 1,829 &  71,341,410 \\ 
  chr15 & 102,531,392 &  81,694,769 &  57,735 &  55,825 & 0.03 &    44 &   8,264,635 \\ 
   \rowcolor[gray]{0.9}chr16 &  90,354,753 &  78,884,753 &  70,250 &  62,564 & 0.04 & 3,002 &  33,853,738 \\ 
  chr17 &  81,195,210 &  77,795,210 &  66,052 &  62,787 & 0.04 &   443 &  19,256,013 \\ 
   \rowcolor[gray]{0.9}chr18 &  78,077,248 &  74,657,248 &  50,666 &  46,281 & 0.03 &   808 &  74,656,467 \\ 
  chr19 &  59,128,983 &  55,808,983 &  64,474 &  49,008 & 0.05 & 5,787 &  23,974,122 \\ 
   \rowcolor[gray]{0.9}chr20 &  63,025,520 &  59,505,520 &  46,611 &  44,671 & 0.04 &    89 &  42,919,877 \\ 
  chr21 &  48,129,895 &  35,108,702 &  36,208 &  24,921 & 0.05 & 4,920 &     316,273 \\ 
   \rowcolor[gray]{0.9}chr22 &  51,304,566 &  34,894,566 &  28,892 &  27,808 & 0.04 &    54 &     661,661 \\ 
  chrX & 155,270,560 & 151,100,560 & 104,959 &  96,017 & 0.03 & 3,752 & 104,487,419 \\ 
   \rowcolor[gray]{0.9}chrY &  59,373,566 &  25,653,566 &  10,983 &   9,112 & 0.02 &   383 &  25,653,527 \\ 
   \hline
\hline
\end{longtable}
}\end{center}

\subsection{Depth by genomic feature}

\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4.5in, page=2]{bamchop-depth-feature}
\caption{\textbf{Average depth of genomic features.} Genomic features are regions annotated based on previous knowledge, such as the RefSeq gene track downloaded from UCSC genome browser. Many applications of high-throughput sequencing technologies, such as exome sequencing and RNA-seq, expect higher depth at exons.}
\end{figure}
\end{center}

\pagebreak

\section{Sequencing quality}
This section summarizes the sequencing quality scores assigned by the sequencer to single bases in each sequencing read and stored in the \textbf{<QUAL>} field of BAM files.
\vspace*{1\baselineskip}
\\{\textbf{Quality score summary:}}
\begin{Schunk}
\begin{Soutput}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2.00   37.00   40.00   38.77   41.00   41.00 
\end{Soutput}
\end{Schunk}

\subsection{Quality score categories}
\begin{SCtable}[1][!ht]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Score & Count & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
Score=0 &         0 &  0.00 \\ 
  Score$>$=5 & 6,115,009 & 99.88 \\ 
   \rowcolor[gray]{0.9}Score$>$=10 & 6,109,807 & 99.80 \\ 
  Score$>$=13 & 6,107,202 & 99.75 \\ 
   \rowcolor[gray]{0.9}Score$>$=20 & 6,093,994 & 99.54 \\ 
  Score$>$=30 & 6,025,542 & 98.42 \\ 
   \rowcolor[gray]{0.9}Score$>$=40 & 3,472,376 & 56.72 \\ 
  Score=41 & 2,719,313 & 44.42 \\ 
   \hline
\end{tabular}\caption{\textbf{Score categories.} The number and percentage of base calls having the quality socre equal to or higher than given values.)}
\end{SCtable}

\subsection{Overall score distribution}

\begin{center}
\begin{SCfigure}[1][!ht]
\includegraphics[width=4in, height=3in]{bamchop-qual-distribution}
\caption{\textbf{Score distribution.} This distribution is based on all bases of randomly selected sequencing reads, so position-specific sequencing quality is not considered (see below). The quality scores are calculated by subtracting 33 from the integers corresponding to the ASCII characters in \textbf{<QUAL>}. If the convention of Sanger sequencing was applied to generate the ASCII characters, they are equal to -10*Log10(p value), where p value is the likelihood of incorrect base call.}
\end{SCfigure}
\end{center}

\subsection{Position-specific score distribution}

\begin{center}
\begin{figure}[H]
\includegraphics[width=7in, height=5in, page=1]{bamchop-qual-position}
\caption{\textbf{Position-specific sequencing scores.} This plot shows quality scores at different positions within reads. The dashed lines represents the means of quality scores at different positions; whereas the heat gradient corresponds to percentiles.}
\end{figure}
\end{center}


\pagebreak
\section{Mapping to reference}
This section summarizes the mapping of sequencing reads to reference chromosomes.
\subsection{Mapping length}
Mapping length corresponds to the \textbf{<QWIDTH>} field in BAM files, which is the number of bases in a read mapped to reference. Hard clipping reduces mapping length while soft clipping does not.
\vspace*{1\baselineskip}
\\{\textbf{Mapping length summary:}}
\begin{Schunk}
\begin{Soutput}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   25.0    49.0    49.0    48.5    49.0    49.0 
\end{Soutput}
\end{Schunk}


\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4in]{bamchop-mapping-length}
\caption{\textbf{Frequency of mapping lengths.} }
\end{figure}
\end{center}

\subsection{Mapping flag}
Mapping flag is stored in the \textbf{<FLAG>} field of BAM files. It uses a series of bitwise codes to represent different combinations of mapping results:
\begin{center}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{ll}
  \hline
Bitwise & Description \\ 
  \hline
0X1 & template having multiple segments in sequencing \\ 
  0X2 & each segment properly aligned according to the aligner \\ 
  0X4 & segment unmapped \\ 
  0X8 & next segment in the template unmapped \\ 
  0X10 & SEQ being reverse complemented \\ 
  0X20 & SEQ of the next segment in the template being reversed \\ 
  0X40 & the first segment in the template \\ 
  0X80 & the last segment in the template \\ 
  0X100 & secondary alignment \\ 
  0X200 & not passing quality controls \\ 
  0X400 & PCR or optical duplicate \\ 
   \hline
\end{tabular}\end{center}

\subsubsection{Mapping flag categories}
\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Code & Count & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
0X1 &          0 &  0.00 \\ 
  0X2 &          0 &  0.00 \\ 
   \rowcolor[gray]{0.9}0X4 &          0 &  0.00 \\ 
  0X8 &          0 &  0.00 \\ 
   \rowcolor[gray]{0.9}0X10 & 13,576,225 & 49.99 \\ 
  0X20 &          0 &  0.00 \\ 
   \rowcolor[gray]{0.9}0X40 &          0 &  0.00 \\ 
  0X80 &          0 &  0.00 \\ 
   \rowcolor[gray]{0.9}0X100 & 25,094,620 & 92.40 \\ 
  0X200 &          0 &  0.00 \\ 
   \rowcolor[gray]{0.9}0X400 &          0 &  0.00 \\ 
   \hline
\end{tabular}\caption{\textbf{Mapping flag categories.} The total number and percentage of reads flagged by each category.}
\end{SCtable}

\subsubsection{Flag value breakdown}
\begin{center}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\tiny
\begin{longtable}{|r|r|r|r|r|r|r|r|r|r|r|r|r|r|}
\caption{The breakdown of values into flag categories.} \\ 
  \hline
Value & Count & Percentage & 0X1 & 0X2 & 0X4 & 0X8 & 0X10 & 0X20 & 0X40 & 0X80 & 0X100 & 0X200 & 0X400 \\ 
  \hline
0 &  1,031,106 &  3.8 & - & - & - & - & - & - & - & - & - & - & - \\ 
   \rowcolor[gray]{0.9}16 &  1,032,580 &  3.8 & - & - & - & - & X & - & - & - & - & - & - \\ 
  256 & 12,550,975 & 46.2 & - & - & - & - & - & - & - & - & X & - & - \\ 
   \rowcolor[gray]{0.9}272 & 12,543,645 & 46.2 & - & - & - & - & X & - & - & - & X & - & - \\ 
   \hline
\hline
\end{longtable}
}\end{center}

\subsection{Mapping score}
Mapping scores are assigned by the alignment program to indicate the likelihood of false alignment and stored in the \textbf{<MAPQ>} field of BAM files. Higher score usually means longer alignment, less mismatch, and/or higher uniqueness. 
\vspace*{1\baselineskip}
\\{\textbf{Mapping score summary:}}
\begin{Schunk}
\begin{Soutput}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00   70.00   45.49   70.00   70.00 
\end{Soutput}
\end{Schunk}

\subsubsection{Mapping score categories}
\vspace*{1\baselineskip}
\begin{SCtable}[1][!ht]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Score & Count & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
mapq=0 & 33,367 & 26.66 \\ 
  mapq$>$=1 & 91,794 & 73.34 \\ 
   \rowcolor[gray]{0.9}mapq$>$=2 & 89,353 & 71.39 \\ 
  mapq$>$=3 & 88,212 & 70.48 \\ 
   \rowcolor[gray]{0.9}mapq$>$=4 & 86,275 & 68.93 \\ 
  mapq$>$=5 & 86,238 & 68.90 \\ 
   \rowcolor[gray]{0.9}mapq$>$=10 & 85,976 & 68.69 \\ 
  mapq$>$=20 & 84,324 & 67.37 \\ 
   \rowcolor[gray]{0.9}mapq$>$=30 & 80,873 & 64.62 \\ 
  mapq$>$=40 & 80,100 & 64.00 \\ 
   \rowcolor[gray]{0.9}mapq=70 & 76,440 & 61.07 \\ 
   \hline
\end{tabular}\caption{\textbf{Mapping score categories.} The total number and percentage of reads having mapping scores equal to or higher than given values.}
\end{SCtable}

\subsubsection{Overall score distribution}

\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4in]{bamchop-mapq-distribution}
\caption{\textbf{Mapping score distribution. } By definition, mapping quality equals to -10*Log10(p value), where p value is the likelihood of incorrect mapping; however, its calculation depends on individual programs.}
\end{figure}
\end{center}

\subsection{Mismatch (CIGAR)}
SAM uses the \textbf{<CIGAR>} field to compactly represent alignments. CIGAR characters are used in concert with lengths to describe various types of matching, mismatching, clipping, padding and splicing events within an alignment.
\subsubsection{Mismatch categories}
\begin{center}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{ll}
  \hline
Bitwise & Description \\ 
  \hline
M & alignment match (can be a sequence match or mismatch) \\ 
  I & insertion to the reference \\ 
  D & deletion from the reference \\ 
  N & skipped region from the reference \\ 
  S & soft clipping (clipped sequences present in SEQ) \\ 
  H & hard clipping (clipped sequences NOT present in SEQ) \\ 
  P & padding (silent deletion from padded reference) \\ 
  = & sequence match \\ 
  X & sequence mismatch \\ 
   \hline
\end{tabular}\end{center}

\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Category & Count & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
M & 2,063,686 & 100.00 \\ 
  I &    18,302 &   0.89 \\ 
   \rowcolor[gray]{0.9}D &     8,832 &   0.43 \\ 
  S &   158,755 &   7.69 \\ 
   \rowcolor[gray]{0.9}H &    68,351 &   3.31 \\ 
   \hline
\end{tabular}\caption{\textbf{Mismatch categories} The total number and percentage of reads having specific types of mismatches.}
\end{SCtable}

\subsubsection{Gapped alignment}
\textbf{Not reads having gapped alignment.}

\begin{center}
\begin{SCfigure}[1][h!]
\includegraphics[width=4in, height=3in]{bamchop-gap-size}
\caption{\textbf{Distribution of gap size.} If the alignment program tried to align sub-sequence of the same read to remote locations, \textbf{<CIGAR>} will provide the size of gapped regions}
\end{SCfigure}
\end{center}


\subsection{Duplicated mapping}
Duplicated mapping refers to multiple reads having their first base mapped to the same strand and location. Duplication level is the number of reads sharing the same duplicated mapping. It is an indicator of the effect of PCR artifact, but also depends on local and overall sequencing depth.

\subsubsection{Duplication level categories}
\textbf{The average number of duplicated reads at each mapping location is 1.113.}
\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|r|}
  \hline
Level & Location\_count & Read\_count & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
1 & 1,787,091 & 1,787,091 & 86.597 \\ 
  2 & 56,725 & 113,450 &  5.497 \\ 
   \rowcolor[gray]{0.9}3 & 4,185 & 12,555 &  0.608 \\ 
  4 & 1,281 & 5,124 &  0.248 \\ 
   \rowcolor[gray]{0.9}5 & 698 & 3,490 &  0.169 \\ 
  6 & 472 & 2,832 &  0.137 \\ 
   \rowcolor[gray]{0.9}7 & 281 & 1,967 &  0.095 \\ 
  8 & 248 & 1,984 &  0.096 \\ 
   \rowcolor[gray]{0.9}9 & 174 & 1,566 &  0.076 \\ 
  10 & 151 & 1,510 &  0.073 \\ 
   \rowcolor[gray]{0.9}$>$10 & 2,261 & 132,117 &  6.402 \\ 
   \hline
\end{tabular}\caption{\textbf{Duplication level categories.} Numbers of mapping locations and reads having the duplication levels of the given values.}
\end{SCtable}

\subsubsection{Overall duplication distribution}

\begin{center}
\begin{figure}[H]
\includegraphics[width=6in, height=3.2in]{bamchop-dup-distribution}
\caption{textbf{Distribution of duplication levels}. The x-axis indicates the number of reads sharing the same mapping location of their 5'-end and the y-axis is the total occurance of each level. Only reads mapped to the forward strand and the first 10 million reads of each chromosome was used to reduce computation.}
\end{figure}
\end{center}

\subsection{Paired reads}
\textbf{No information about paired-end reads is available in this BAM file.}

\subsubsection{Read count summary}
\textbf{Not applicable.}
\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Category & Count & Percent \\ 
  \rowcolor[gray]{0.9} \hline
Total paired-end reads & 0.00 & 0.00 \\ 
   \hline
\end{tabular}\caption{\textbf{Paired-end reads.} Read counts in this table are based on the "flag" field in BAM file. Properly mapping paired-end reads are reads mapped to the opposite strand of the same chromosome. }
\end{SCtable}

\subsubsection{Insertion size of paired reads}
\textbf{Not applicable.}


\begin{center}
\begin{SCfigure}[1][h!]
\includegraphics[width=4in, height=3in]{bamchop-pair-insert}
\caption{\textbf{Distribution of insertion size. }Insertion size is the distance between the mapping locations of the 5'-end of paired reads. It represents the size of DNA fragment to be sequenced.}
\end{SCfigure}
\end{center}

\pagebreak
\section{Base frequency}
This section summarizes the frequency of nucleic acid bases within sequencing reads in order to identify sequencing bias. 

\subsection{Base N frequency}
\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|r|}
  \hline
 & Total & N & Percentage \\ 
  \rowcolor[gray]{0.9} \hline
Base & 6,122,337 & 191 & 0.0031 \\ 
  Read &   125,161 & 179 & 0.1430 \\ 
   \hline
\end{tabular}\caption{\textbf{N base frequency.} The Ns in the reads are assigned by the sequencing machine to suggest that the base cannot be determined due to low quality or other reasons. This table shows the number and percentage of Ns and reads including any Ns. Ns are then excluded from the following analyses of base frequency. }
\end{SCtable}

\subsection{Expected vs. observed frequency}
\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|r|r|r|}
  \hline
 & A & C & G & T & GC \\ 
  \rowcolor[gray]{0.9} \hline
Expected(\%) & 29.51 &  20.47 &  20.48 & 29.55 &  40.94 \\ 
  Observed(\%) & 26.41 &  23.51 &  23.40 & 26.69 &  46.91 \\ 
   \rowcolor[gray]{0.9}Observed/Expected(\%) & 89.49 & 114.87 & 114.26 & 90.32 & 114.57 \\ 
   \hline
\end{tabular}\caption{\textbf{Expected vs. observed base frequency.} The expected base frequency is based on the whole reference genome and the observed frequency is the base frequency in sequencing reads. Their ratio reflects the sequencing bias of nucleic acid bases.}
\end{SCtable}

\subsection{GC content}
\begin{center}
\begin{SCfigure}[1][h!]
\includegraphics[width=3.2in, height=2.5in]{bamchop-base-gc}
\caption{\textbf{GC content.} Percentage of C/G bases within each read.}
\end{SCfigure}
\end{center}

\subsection{Position-specific base frequency}
Position-specific frequency of bases indicates whether there is a sequencing bias at both ends of the reads. The bias can be introduced via a variety of sources, such as DNA fragmentation and primer contamination. 
\subsubsection{Single base}
\begin{center}
\begin{figure}[h!]
\subfigure{\includegraphics[width=3.33in, height=2in, page=2]{bamchop-base-fst-lst} }
\subfigure{\includegraphics[width=3.33in, height=2in, page=4]{bamchop-base-fst-lst} }
\caption{\textbf{Single base frequency at both ends.}The base frequency of the first and last 10 bases (the rightmost is the last base) of reads. The frequency was normalized by the overall base frequency with sequencing reads, so this summary indicates the preference of sequencing to start with a given nucleic acid base.}
\end{figure}
\end{center}

\subsubsection{First two bases}

\begin{center}
\begin{SCfigure}[1][h!]
\includegraphics[width=2.5in, height=2.5in]{bamchop-base-two}
\caption{\textbf{First two base combination.}\small{This plot summarizes the frequency of the two-base combinations at the 5'-end of reads. The size of the blocks represent their relative frequency after adjusted by their expected frequency based on the position-specific frequency of the first two bases.}}
\end{SCfigure}
\end{center}

\subsubsection{5-mer frequency}
The frequency of 5-mer at both ends of reads.
\begin{center}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\scriptsize
\begin{longtable}{|r|r|r|r|}
\caption{Lowest frequency} \\ 
  \hline
5-mer & Expected\_count & Observed\_count & Observed/Expected \\ 
  \hline
$|$CGCGT & 101.50 & 1 & 0.0099 \\ 
   \rowcolor[gray]{0.9}$|$CGACG & 103.42 & 2 & 0.0193 \\ 
  $|$CGTCG & 103.45 & 3 & 0.0290 \\ 
   \rowcolor[gray]{0.9}$|$TCGGT & 100.79 & 3 & 0.0298 \\ 
  CGACG$|$ & 102.08 & 4 & 0.0392 \\ 
   \rowcolor[gray]{0.9}TACGA$|$ & 131.82 & 4 & 0.0303 \\ 
  $|$TCGAC &  95.07 & 5 & 0.0526 \\ 
   \rowcolor[gray]{0.9}ACGCG$|$ & 100.44 & 5 & 0.0498 \\ 
  $|$TCGTA & 115.20 & 6 & 0.0521 \\ 
   \rowcolor[gray]{0.9}$|$GTACG & 120.59 & 6 & 0.0498 \\ 
   \hline
\hline
\end{longtable}
}% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\scriptsize
\begin{longtable}{|r|r|r|r|}
\caption{Highest frequency} \\ 
  \hline
5-mer & Expected\_count & Observed\_count & Observed/Expected \\ 
  \hline
$|$TTTTT & 175.40 & 608 & 3.47 \\ 
   \rowcolor[gray]{0.9}AAAAA$|$ & 167.20 & 565 & 3.38 \\ 
  TTTTT$|$ & 155.53 & 510 & 3.28 \\ 
   \rowcolor[gray]{0.9}$|$AAAAA & 176.87 & 458 & 2.59 \\ 
  $|$CCCAG &  90.94 & 427 & 4.70 \\ 
   \rowcolor[gray]{0.9}CTGGG$|$ &  99.25 & 391 & 3.94 \\ 
  $|$CTGGG & 109.91 & 381 & 3.47 \\ 
   \rowcolor[gray]{0.9}$|$ATTTT & 182.77 & 358 & 1.96 \\ 
  $|$AGAGA & 138.04 & 358 & 2.59 \\ 
   \rowcolor[gray]{0.9}AAAAT$|$ & 164.00 & 354 & 2.16 \\ 
   \hline
\hline
\end{longtable}
}% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\scriptsize
\begin{longtable}{|r|r|r|r|}
\caption{Highest relative enrichment} \\ 
  \hline
5-mer & Expected\_count & Observed\_count & Observed/Expected \\ 
  \hline
$|$CCCAG &  90.94 & 427 & 4.70 \\ 
   \rowcolor[gray]{0.9}CTGGG$|$ &  99.25 & 391 & 3.94 \\ 
  $|$CTGGG & 109.91 & 381 & 3.47 \\ 
   \rowcolor[gray]{0.9}$|$TTTTT & 175.40 & 608 & 3.47 \\ 
  AAAAA$|$ & 167.20 & 565 & 3.38 \\ 
   \rowcolor[gray]{0.9}GAGGC$|$ & 103.94 & 350 & 3.37 \\ 
  CCTCC$|$ & 101.43 & 341 & 3.36 \\ 
   \rowcolor[gray]{0.9}$|$CCAGG & 100.18 & 332 & 3.31 \\ 
  TTTTT$|$ & 155.53 & 510 & 3.28 \\ 
   \rowcolor[gray]{0.9}CCCAG$|$ & 102.49 & 328 & 3.20 \\ 
  GGAGG$|$ & 104.02 & 321 & 3.09 \\ 
   \rowcolor[gray]{0.9}CCAGG$|$ & 103.22 & 318 & 3.08 \\ 
  $|$GGAGG & 110.16 & 336 & 3.05 \\ 
   \rowcolor[gray]{0.9}$|$CCTCC &  89.09 & 270 & 3.03 \\ 
  GCCTC$|$ & 104.95 & 317 & 3.02 \\ 
   \rowcolor[gray]{0.9}GCTGG$|$ & 101.64 & 306 & 3.01 \\ 
   \hline
\hline
\end{longtable}
}\end{center}
\newpage

\section{ChIP-seq}
This section of the report summarizes information related to a ChIP-seq experiment. 


\subsection{Strand-strand correlation}
Since sequencing usually starts from the 5-prime end of DNA fragments, reads mapped to the forward and reverse strands were skewed to the left and right respectively. While we expect a positive correlation between the two strands if reads were enriched around ChIP-ed regions, the forward strand needs to be shifted towards the right, or vice versa, to achieve the maximal strand correlation. The assoication between correlation coefficients and numbers of bases to shift indicates the distribution of DNA fragment sizes.


\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4.5in, page=1]{bamchop-chip-strand-corr}
\caption{\textbf{Strand-strand correlation vs. shifting.}The x-axis is the number of bases to shift the forward strand towards the right. Correlation was calculated between the 5-prime end of mapping locations after removing duplicated mappings.}
\end{figure}
\end{center}

\subsection{Peaks}
This section of the report is a quick summary of peaked regions without using specifically designed peak calling program. All reads were extended to  base pairs at the 3-prime end. A peak is defined here as a continuous region with at least 1X depth. 

\begin{SCtable}[1][h!]
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
\begin{tabular}{|r|r|r|}
  \hline
Height & Count & Average\_width \\ 
  \rowcolor[gray]{0.9} \hline
$>$=10 & 976 & 1,154.23 \\ 
  $>$=25 & 321 & 1,927.70 \\ 
   \rowcolor[gray]{0.9}$>$=50 & 154 & 2,452.29 \\ 
  $>$=100 &  69 & 2,402.51 \\ 
   \rowcolor[gray]{0.9}$>$=200 &  39 & 2,468.41 \\ 
  $>$=500 &  27 &   979.15 \\ 
   \rowcolor[gray]{0.9}$>$=1,000 &  24 & 1,001.21 \\ 
  $>$=5,000 &   6 & 1,229.33 \\ 
   \rowcolor[gray]{0.9}$>$=10,000 &   3 &   592.00 \\ 
  =14,985 &   1 &   632.00 \\ 
   \hline
\end{tabular}\caption{\textbf{Peak summary.} Numbers of peaks with given depth and their average width.}
\end{SCtable}

\subsubsection{Peak height}
Peak height is the maximal sequencing depth within a peak.
\begin{center}
\begin{figure}[H]
\includegraphics[width=7in, height=4.5in, page=1]{bamchop-chip-peak-height}
\caption{\textbf{Peak height distribution.}}
\end{figure}
\end{center}

\subsubsection{Peak width}
Peak width is the size of a continuous region with a minimum of 1X depth.
\vspace*{1\baselineskip}
\\{\textbf{Peak width summary:}}
\begin{Schunk}
\begin{Soutput}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  200.0   200.0   200.0   220.8   200.0 30110.0 
\end{Soutput}
\end{Schunk}


\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4.5in, page=1]{bamchop-chip-peak-width}
\caption{\textbf{Peak width distribution.}\small{}}
\end{figure}
\end{center}

\subsubsection{Peak frequency by genomic feature}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\tiny
\begin{longtable}{|r|r|r|r|r|r|r|}
\caption{Number of peaks mapped to genomic features.} \\ 
  \hline
Feature & Promoter & 5-UTR & Coding & Intron & 3-UTR & Exon \\ 
  \hline
Height$>$=10 & 38 & 34 & 104 & 248 & 7 & 124 \\ 
   \rowcolor[gray]{0.9}Height$>$=25 &  7 &  1 &  15 &  71 & 3 &  24 \\ 
  Height$>$=50 &  5 &  0 &   5 &  38 & 1 &  12 \\ 
   \rowcolor[gray]{0.9}Height$>$=100 &  4 &  0 &   1 &  24 & 1 &   6 \\ 
  Height$>$=200 &  2 &  0 &   0 &  11 & 0 &   2 \\ 
   \rowcolor[gray]{0.9}Height$>$=500 &  2 &  0 &   0 &  11 & 0 &   2 \\ 
  Height$>$=1000 &  2 &  0 &   0 &  11 & 0 &   2 \\ 
   \rowcolor[gray]{0.9}Height$>$=5000 &  1 &  0 &   0 &   3 & 0 &   1 \\ 
  Height$>$=10000 &  0 &  0 &   0 &   2 & 0 &   0 \\ 
   \rowcolor[gray]{0.9}Height$>$=14985 &  0 &  0 &   0 &   1 & 0 &   0 \\ 
   \hline
\hline
\end{longtable}
}
\begin{center}
\begin{figure}[H]
\includegraphics[width=7in, height=4.5in, page=1]{bamchop-chip-peak-by-feature}
\caption{\textbf{Peak frequency within genomic features.}The dashed line is the overall frequency of peaks with depth no less than 10 within the whole genome.}
\end{figure}
\end{center}

\subsubsection{Top peaks}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\scriptsize
\begin{longtable}{|r|r|r|r|r|}
\caption{Top 20 peaks with the highest height.} \\ 
  \hline
Chromosome & Start & End & Width & Height \\ 
  \hline
chr8 &  70,602,155 &  70,602,786 &   632 & 14,985 \\ 
   \rowcolor[gray]{0.9}chr1 &  91,852,607 &  91,853,314 &   708 & 11,185 \\ 
  chr4 &  70,296,491 &  70,296,926 &   436 & 11,130 \\ 
   \rowcolor[gray]{0.9}chr2 & 133,011,216 & 133,013,962 & 2,747 &  6,719 \\ 
  chr21 &   9,825,283 &   9,827,730 & 2,448 &  6,514 \\ 
   \rowcolor[gray]{0.9}chr19 &  24,183,920 &  24,184,324 &   405 &  5,787 \\ 
  chrX & 108,297,196 & 108,298,002 &   807 &  4,813 \\ 
   \rowcolor[gray]{0.9}chr12 &  20,704,189 &  20,704,656 &   468 &  4,758 \\ 
  chr19 &  36,066,333 &  36,066,921 &   589 &  3,590 \\ 
   \rowcolor[gray]{0.9}chr5 & 174,541,594 & 174,542,319 &   726 &  3,387 \\ 
  chr11 &  77,597,130 &  77,597,846 &   717 &  3,385 \\ 
   \rowcolor[gray]{0.9}chr16 &  33,962,396 &  33,966,603 & 4,208 &  3,016 \\ 
  chr13 &  31,418,041 &  31,418,658 &   618 &  2,677 \\ 
   \rowcolor[gray]{0.9}chr1 & 145,277,150 & 145,277,647 &   498 &  1,912 \\ 
  chr14 &  90,341,021 &  90,341,601 &   581 &  1,831 \\ 
   \rowcolor[gray]{0.9}chr1 & 120,543,552 & 120,544,208 &   657 &  1,811 \\ 
  chr2 &       9,841 &      10,465 &   625 &  1,497 \\ 
   \rowcolor[gray]{0.9}chr1 & 121,482,686 & 121,485,607 & 2,922 &  1,441 \\ 
  chr2 & 133,036,355 & 133,036,887 &   533 &  1,429 \\ 
   \rowcolor[gray]{0.9}chr1 & 237,766,173 & 237,766,699 &   527 &  1,388 \\ 
   \hline
\hline
\end{longtable}
}

\subsection{TSS}
This section of the report summarizes sequencing depth around transcription start sites (TSS).
\subsubsection{Strand-specific depth around TSS}
\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4.5in, page=1]{bamchop-chip-tss-loc}
\caption{\textbf{Read frequency around TSS.}This plot shows the frequency of reads whose 5-prime end was mapped around TSS of RefSeq genes. The read counts were normalized by the global average after duplicated mapping was not removed.}
\end{figure}
\end{center}

\subsubsection{Read counts around individual TSSs}
Read counts around TSS of individual genes.
\vspace*{1\baselineskip}
\\{\textbf{Read count summary:}}
\begin{Schunk}
\begin{Soutput}
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
   0.000    1.000    2.000    3.184    3.000 1080.000 
\end{Soutput}
\end{Schunk}

\begin{center}
\begin{figure}[H]
\includegraphics[width=6.5in, height=4.5in, page=1]{bamchop-chip-tss-gene}
\caption{\textbf{Read count distribution of genes.}This plot shows the distribution of read counts within the [-1kb, 1kb] region of RefSeq TSSs. Duplicated mapping was excluded.}
\end{figure}
\end{center}

% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
{\scriptsize
\begin{longtable}{|r|r|r|r|}
\caption{Top 21 genes with the highest read counts around TSS} \\ 
  \hline
RefSeq\_ID & Sense & Antisense & Total \\ 
  \hline
NR\_037458 & 532 & 548 & 1,080 \\ 
   \rowcolor[gray]{0.9}NR\_037421 & 390 & 376 &   766 \\ 
  NR\_033770 & 293 & 329 &   622 \\ 
   \rowcolor[gray]{0.9}NR\_040095 & 211 & 200 &   411 \\ 
  NR\_030386 & 106 & 120 &   226 \\ 
   \rowcolor[gray]{0.9}NR\_038368 & 100 & 108 &   208 \\ 
  NR\_027020 &  53 &  35 &    88 \\ 
   \rowcolor[gray]{0.9}NR\_031608 &  53 &  34 &    87 \\ 
  NM\_022133 &  21 &  18 &    39 \\ 
   \rowcolor[gray]{0.9}NM\_152836 &  21 &  18 &    39 \\ 
  NM\_152837 &  21 &  18 &    39 \\ 
   \rowcolor[gray]{0.9}NM\_005604 &  20 &  14 &    34 \\ 
  NR\_037416 &  16 &  15 &    31 \\ 
   \rowcolor[gray]{0.9}NM\_022359 &  13 &  18 &    31 \\ 
  NM\_182704 &  19 &  10 &    29 \\ 
   \rowcolor[gray]{0.9}NM\_006262 &  15 &  14 &    29 \\ 
  NM\_003013 &  16 &  13 &    29 \\ 
   \rowcolor[gray]{0.9}NM\_001042544 &  10 &  18 &    28 \\ 
  NR\_047517 &  17 &  11 &    28 \\ 
   \rowcolor[gray]{0.9}NM\_031912 &  14 &  14 &    28 \\ 
  NM\_181519 &  14 &  14 &    28 \\ 
   \hline
\hline
\end{longtable}
}\newpage

\section{Alerts}
% latex table generated in R 2.15.2 by xtable 1.7-0 package
% Tue Apr 30 06:56:35 2013
 --- GC contents of reads are more than 110\% (114.6\%) of expected percentage. \\ 
  --- There are 16 5-mers overrepresented at either end of reads. \\ \end{document}
